#!/bin/bash

PS3="Which config do you want to use? "

rm -rf ~/.kube/config
files=($(ls ~/.kube))
selectfiles=()

for file in "${files[@]}"
do
  if [[ -f ~/.kube/$file ]]; then 
    line=$(head -n 1 ~/.kube/$file)
    if [[ $line = "apiVersion: v1" ]]; then
            selectfiles+=($file)
    fi
  fi 
done

select file in "${selectfiles[@]}"
do
  echo "Selected config: $file"
  cp ~/.kube/$file ~/.kube/config
  exit 1
done
