#!/bin/bash

PS3="Which config do you want to use? "

rm -rf ~/.kube/config
files=($(ls ~/.kube))
selectfiles=()

for file in "${files[@]}"
do
  line=$(head -n 1 ~/.kube/$file)
  if [[ $line = "apiVersion: v1" ]]; then
          selectfiles+=($file)
  fi
done

select file in "${selectfiles[@]}"
do
  echo "Selected config: $file"
  KUBECONFIG=$file
  cp ~/.kube/$file ~/.kube/config
  exit 1
done