#!/bin/bash

rm -rf ~/.kube/config
files=($(ls ~/.kube))

PS3="Which config do you want to use? "

select file in "${files[@]}"
do
  echo "Selected config: $file"
  KUBECONFIG=$file
  cp ~/.kube/$file ~/.kube/config
  exit 1
done
